---
title: "Managing Data Assignment"
author: |
  | Data Science for Agriculture and Natural Resources
  | PLNT 5413 - Fall `r format(Sys.Date(),'%Y')`
output: 
  pdf_document:
    fig_caption: false
link-citations: true
urlcolor: blue
margin: 1in
fontsize: 12pt
geometry: "left=1in,right=1in,top=1in,bottom=1.25in"
header-includes:
- \usepackage{lastpage}
- \usepackage{fancyhdr}
- \newcommand{\aspace}[1]{\vspace{#1\baselineskip}}
- \renewcommand{\headrulewidth}{0pt}
- \fancypagestyle{plain}{ \fancyhf{} \fancyfoot[C]{\aspace{2}Page \thepage~of~\pageref{LastPage}} }
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot[C]{\small \thetitle \\ Data Science for Agriculture and Natural Resources\\PLNT 5413 - Fall `r format(Sys.Date(),'%Y')`\\ Page \thepage~of~\pageref{LastPage}}
---

## Organizing Data in Spreadsheets (50 pts)

Using *Tidy Data* principles, design a spreadsheet (or set of spreadsheets) and associated Readme file(s) that you will use for your semester project. For the Readme file you may wish to adapt the [Cornell University’s Research Data Management Service Group template](https://cornell.app.box.com/v/ReadmeTemplate). Among other details, be sure to include:

- Space for tracking notes on the data capture/organization process
- A data dictionary that defines variable names (including units)
- Quality control procedures you will use

For the spreadsheet, be sure to:

- Put variables in columns and observations in rows
- Avoid placing multiple pieces of information in a single cell
- Avoid the "Common Spreadsheet Errors" discussed in the *Data Organization in Spreadsheets* reading
- Use the `Data Validation` or `Validity` tool for quality assurance
- Partially fill in your spreadsheet with example data to demonstrate how you will use it

## Writing a Data Management Plan (50 pts)

Using the [OSU Libraries Data Management Plan Template](http://bit.ly/27TWU3F), create a 1-2 page Data Management Plan for your semester project. You may also wish to refer to the [Rubric for assessment of NSF data management plans](https://mfr.osf.io/render?url=https://osf.io/jj7dm/?action=download%26mode=render). Be sure to include:

- A brief introduction to the project
- Types and quantities of data that will be produced (including method of collection/capture)
- Standards that you will use for data and metadata
- Policies for data access and sharing/re-use
- Plans for data archiving and preservation