---
title: "Wrangling Data - Organizing Data in Spreadsheets"
author: |
  | Data Science for Agriculture and Natural Resources
  | PLNT 5413 - Fall `r format(Sys.Date(),'%Y')`
output: 
  pdf_document:
    fig_caption: false
link-citations: true
urlcolor: blue
margin: 1in
fontsize: 12pt
geometry: "left=1in,right=1in,top=1in,bottom=1.25in"
header-includes:
- \usepackage{titling}
- \usepackage{lastpage}
- \usepackage{fancyhdr}
- \newcommand{\aspace}[1]{\vspace{#1\baselineskip}}
- \renewcommand{\headrulewidth}{0pt}
- \fancypagestyle{plain}{ \fancyhf{} \fancyfoot[C]{\aspace{2}Page \thepage~of~\pageref{LastPage}} }
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot[C]{\small \thetitle \\ Data Science for Agriculture and Natural Resources\\PLNT 5413 - Fall `r format(Sys.Date(),'%Y')`\\ Page \thepage~of~\pageref{LastPage}}
---

Using *Tidy Data* principles, design a set of files for data capture of the variables in the table below. Be sure to:

- Create a `readme.txt` that includes a definition of all variable names used in the dataset including units (e.g. NDVI would need to be defined as Normalized Difference Vegetation Index)
-  Avoid the "Common Spreadsheet Errors" discussed in [Formatting problems](https://datacarpentry.org/spreadsheet-ecology-lesson/02-common-mistakes/index.html)
- Avoid using problematic column/field names (described here [Formatting problems](https://datacarpentry.org/spreadsheet-ecology-lesson/02-common-mistakes/index.html))
- Use the `Data Validation` or `Validity` tool for quality assurance for variables with well-defined ranges (see [Quality control](https://datacarpentry.org/spreadsheet-ecology-lesson/04-quality-control/index.html))
- Handle dates using one of the recommended strategies described in [Dates as data](https://datacarpentry.org/spreadsheet-ecology-lesson/03-dates-as-data/index.html).
- Partially fill in your spreadsheet(s) with example data (including some missing data) to demonstrate how you would use it
- Export the spreadsheet(s) as a comma separated (csv) or tab separated file (tsv)

Submit the original spreadsheet(s) as well as the exported version(s).

```{r message=FALSE,echo=FALSE}
library(tidyverse)

variables <- tribble(~Variable,  ~`Type/Possible Units`,                ~`Expected range`,
                   'Site Code',    'character', 'Lahoma, Chickasha, Goodwell, Altus',
                   'Plot Code',      'integer',                                 '1 -- 40',
                 'Sample Date',         'date',   'after Nov 1, 2020; before Jul 1, 2022',
                 'Wheat yield',        'kg/ha or bu/ac',            '0 -- 7000 or 0 -- 100', 'NDVI',         'none',                          '0 -- 1',
                'Ground cover',     '% or fraction',                   '0 -- 100 or 0 -- 1')

knitr::kable(variables,align = 'rrr')

```
