---
title: "Capturing Data - Creating README Metadata"
format:
  pdf:
    template-partials: 
      - ../title.tex
    geometry:
      - margin=1in
    include-in-header:
      text: |
        \usepackage{titling}
        \usepackage{lastpage}
        \usepackage{scrlayer-scrpage}
        \cfoot{\small \thetitle \linebreak Data Science for Agriculture and Natural Resources \linebreak PLNT 5413 - \semester \linebreak Page \thepage~of~\pageref{LastPage}}
editor: source
engine: knitr
---

\newcommand{\semester}{Fall `r format(Sys.Date(), "%Y")`}

## General instructions

A critical part of accurately capturing and curating a dataset is collecting and documenting appropriate metadata. In this assignment you will practice this process using Experiment 502, one of the long-term soil fertility trials at Oklahoma State University. Refer to the information about Experiment 502 available at <https://nue.okstate.edu/Long_Term_Experiments/E502.htm> for details about the experiment.

- Download `README_template.qmd` from Canvas and use it as a template for your own document
- Change the name of the file to `README.qmd`
- Fill in the template using the specific instructions provided below
- Add markdown formatting to enhance legibility of the document
- Render the resulting document as a Markdown file (.md)
- Upload both the README.qmd and README.md files to Canvas

## Specific instructions

### General Information

- Provide a title for the dataset
- Provide name and contact information for:
    - D. Brian Arnall [https://experts.okstate.edu/b.arnall](https://experts.okstate.edu/b.arnall)
    - Yourself
- Date range of data collection
- Information about geographic location

### Data and file overview

- Assume a separate comma separate value (csv) file for each wheat growing season
- Assume the name of each file follows the pattern expmt502_YYYY.csv where YYYY is replaced by the four-digit year of harvest
- Assume the data files are contained inside a subdirectory entitled `data`

### Sharing and access information

- Uses the Creative Commons Attribution-ShareAlike 4.0 International license (CC BY-SA 4.0; see [https://creativecommons.org/licenses/by-sa/4.0/](https://creativecommons.org/licenses/by-sa/4.0/))


### Methodological information

- Include a description of methods for data collection
- Description of methods used for data processing

### Data-specific information

- Variable list with:
    - Full names
    - Definitions
    - Units of measurement
- Definitions of codes used for missing data
- Includes the variables:
    - soil organic matter
    - yield
    - grain nitrogen concentration
    - normalized difference vegetation index (NDVI; see [https://en.wikipedia.org/wiki/Normalized_difference_vegetation_index](https://en.wikipedia.org/wiki/Normalized_difference_vegetation_index))


