---
title: "Capturing Data - Organizing Data in Spreadsheets"
semester: Fall 2023
format:
  pdf:
    template: ../assignment-template.tex
editor: source
engine: knitr
---

Using *Tidy Data* principles, design a set of files for data capture of the variables from Experiment 502, the long-term soil fertility trial at Oklahoma State University that we used for the previous assignment. Refer to the information about Experiment 502 available at <https://nue.okstate.edu/Long_Term_Experiments/E502.htm> for details about the experiment. Be sure to:

-  Avoid the "Common Spreadsheet Errors" discussed in [Formatting problems](https://datacarpentry.org/spreadsheet-ecology-lesson/02-common-mistakes/index.html)
- Avoid using problematic column/field names (described here [Formatting problems](https://datacarpentry.org/spreadsheet-ecology-lesson/02-common-mistakes/index.html))
- Use the `Data Validation` or `Validity` tool for quality assurance for variables with well-defined ranges (see [Quality control](https://datacarpentry.org/spreadsheet-ecology-lesson/04-quality-control/index.html))
- Handle dates using one of the recommended strategies described in [Dates as data](https://datacarpentry.org/spreadsheet-ecology-lesson/03-dates-as-data/index.html).
- Partially fill in your spreadsheet(s) with example data that you can make up (including some missing data) to demonstrate how you would use it
- Export the spreadsheet(s) as a comma separated (csv) or tab separated file (tsv)
- Revise your README.qmd and regenerate README.md to fully document the data file you have created.

Submit the original spreadsheet(s) as well as the exported version(s).
